# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e28e620c46836dda5f26f8d9105bccbf5bdef23c41199e343dd3c2b8c3e1d48dcb0e1512033a24124c48c9ecb451c7bacfffdd89094282ea10c00dc009dc1eb

test:
  secret_key_base: c2ca096676eb9995a1e7b0cc8394395251531ed120f50d5beddb81bcb95f41e4ccdc59e8f03e13ea6aceba3e71794684d3fe195324848d60602983081ed032b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
